

# This file was *autogenerated* from the file quadratic-fact-example.sage
from sage.all_cmdline import *   # import sage library

_sage_const_97 = Integer(97); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
p=_sage_const_97 
F=Integers(p)
R = F['x']; (x,) = R._first_ngens(1)

a=_sage_const_2 
f=x**_sage_const_2 -a

h=_sage_const_1 

while (h.degree()!=_sage_const_1 ):
	r=F.random_element()
	t=(p-_sage_const_1 )/_sage_const_2 
	h=gcd((x-r)**t-_sage_const_1 ,f))

print(h)
g=f/h
print(g)

