

# This file was *autogenerated* from the file quadratic-fact.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
def main():
	p=int(input("Enter a prime: "))
	if (not is_prime(p)):
		print("Not a prime.")
		return

	F=Integers(p)
	R = F['x']; (x,) = R._first_ngens(1)
	a=int(input("Enter the value of a: "))
	a=F(a)
	b=a**((p-_sage_const_1 )/_sage_const_2 )
	if (b==-_sage_const_1 ):
		print("Not a square")
		return	
	
	f=x**_sage_const_2 -a

	h=f
	while (h.degree()!=_sage_const_1 ): 
		r=F.random_element()
		t=(p-_sage_const_1 )/_sage_const_2 
		h=gcd((x-r)**t-_sage_const_1 ,f)
	print(h)
	g=f/h
	print(g)
	
	
if __name__=="__main__":
	main()


	

