

# This file was *autogenerated* from the file ES22BTECH11001.sage
from sage.all_cmdline import *   # import sage library

_sage_const_987013 = Integer(987013); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_987010 = Integer(987010); _sage_const_8 = Integer(8); _sage_const_987009 = Integer(987009); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_986999 = Integer(986999); _sage_const_987007 = Integer(987007); _sage_const_1 = Integer(1)
p=_sage_const_987013 
F=Integers(p)
R = F['x']; (x,) = R._first_ngens(1)

f = x**_sage_const_10  + _sage_const_0 *x**_sage_const_9  + _sage_const_987010 *x**_sage_const_8  + _sage_const_987009 *x**_sage_const_7  + _sage_const_0 *x**_sage_const_6  + _sage_const_7 *x**_sage_const_5  + _sage_const_9 *x**_sage_const_4  + _sage_const_8 *x**_sage_const_3  + _sage_const_987009 *x**_sage_const_2  + _sage_const_986999 *x + _sage_const_987007 

i=_sage_const_1 
g=f
factors=[]
while (g!=_sage_const_1 ):
    xp = power_mod(x, p**i, g)
    h = gcd(g, xp - x)
    if(h!=_sage_const_1 ):
        factors.append(h)
        g = g//h
    i = i+_sage_const_1 
factors

