riscv_asm: ES22BTECH11001_Source_Code.o
	g++ ES22BTECH11001_Source_Code.o -o riscv_asm

ES22BTECH11001_Source_Code.o: ES22BTECH11001_Source_Code.cpp
	g++ -c ES22BTECH11001_Source_Code.cpp

clean: 
	rm *.o riscv_asm